name=trmnl_lib
version=1.0.0
author=Larry Bank
maintainer=Larry Bank
sentence=Easily integrate TRMNL functionality into your project.
paragraph=This library contains the core functionality of TRMNL and allows you to make image requests and display them in your own projects.
category=Data Processing
url=https://github.com/bitbank2/trmnl_lib/
architectures=*
includes=trmnl_lib.h

